// Generated by view binder compiler. Do not edit!
package com.example.covidtrackertwo.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.covidtrackertwo.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivitySignUpBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final LinearLayout SignUp;

  @NonNull
  public final EditText editTextFullName;

  @NonNull
  public final EditText editTextTextEmailAddress;

  @NonNull
  public final EditText editTextTextPassword;

  @NonNull
  public final Button signIn;

  @NonNull
  public final Button signUpButton;

  @NonNull
  public final Button temporaryButton;

  private ActivitySignUpBinding(@NonNull LinearLayout rootView, @NonNull LinearLayout SignUp,
      @NonNull EditText editTextFullName, @NonNull EditText editTextTextEmailAddress,
      @NonNull EditText editTextTextPassword, @NonNull Button signIn, @NonNull Button signUpButton,
      @NonNull Button temporaryButton) {
    this.rootView = rootView;
    this.SignUp = SignUp;
    this.editTextFullName = editTextFullName;
    this.editTextTextEmailAddress = editTextTextEmailAddress;
    this.editTextTextPassword = editTextTextPassword;
    this.signIn = signIn;
    this.signUpButton = signUpButton;
    this.temporaryButton = temporaryButton;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivitySignUpBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivitySignUpBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_sign_up, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivitySignUpBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      LinearLayout SignUp = (LinearLayout) rootView;

      id = R.id.editTextFullName;
      EditText editTextFullName = ViewBindings.findChildViewById(rootView, id);
      if (editTextFullName == null) {
        break missingId;
      }

      id = R.id.editTextTextEmailAddress;
      EditText editTextTextEmailAddress = ViewBindings.findChildViewById(rootView, id);
      if (editTextTextEmailAddress == null) {
        break missingId;
      }

      id = R.id.editTextTextPassword;
      EditText editTextTextPassword = ViewBindings.findChildViewById(rootView, id);
      if (editTextTextPassword == null) {
        break missingId;
      }

      id = R.id.signIn;
      Button signIn = ViewBindings.findChildViewById(rootView, id);
      if (signIn == null) {
        break missingId;
      }

      id = R.id.signUpButton;
      Button signUpButton = ViewBindings.findChildViewById(rootView, id);
      if (signUpButton == null) {
        break missingId;
      }

      id = R.id.temporaryButton;
      Button temporaryButton = ViewBindings.findChildViewById(rootView, id);
      if (temporaryButton == null) {
        break missingId;
      }

      return new ActivitySignUpBinding((LinearLayout) rootView, SignUp, editTextFullName,
          editTextTextEmailAddress, editTextTextPassword, signIn, signUpButton, temporaryButton);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
