// Generated by view binder compiler. Do not edit!
package com.example.covidtrackertwo.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.covidtrackertwo.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class FragmentHistoryBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ConstraintLayout frameLayout4;

  @NonNull
  public final RecyclerView historyRecylerview;

  private FragmentHistoryBinding(@NonNull ConstraintLayout rootView,
      @NonNull ConstraintLayout frameLayout4, @NonNull RecyclerView historyRecylerview) {
    this.rootView = rootView;
    this.frameLayout4 = frameLayout4;
    this.historyRecylerview = historyRecylerview;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentHistoryBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentHistoryBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_history, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentHistoryBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      ConstraintLayout frameLayout4 = (ConstraintLayout) rootView;

      id = R.id.history_recylerview;
      RecyclerView historyRecylerview = ViewBindings.findChildViewById(rootView, id);
      if (historyRecylerview == null) {
        break missingId;
      }

      return new FragmentHistoryBinding((ConstraintLayout) rootView, frameLayout4,
          historyRecylerview);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
