// Generated by view binder compiler. Do not edit!
package com.example.covidtrackertwo.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.cardview.widget.CardView;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.covidtrackertwo.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class FragmentViewLocationBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final CardView cardView;

  @NonNull
  public final Button checkInButton;

  @NonNull
  public final ConstraintLayout frameLayout2;

  @NonNull
  public final TextView locationNameTextView;

  @NonNull
  public final ConstraintLayout locationNameTextview;

  @NonNull
  public final LinearLayout locationsListSelect;

  @NonNull
  public final TextView negativeTextview;

  @NonNull
  public final TextView positiveTextview;

  @NonNull
  public final TextView proportionTextview;

  @NonNull
  public final TextView textView2;

  @NonNull
  public final TextView textView5;

  private FragmentViewLocationBinding(@NonNull ConstraintLayout rootView,
      @NonNull CardView cardView, @NonNull Button checkInButton,
      @NonNull ConstraintLayout frameLayout2, @NonNull TextView locationNameTextView,
      @NonNull ConstraintLayout locationNameTextview, @NonNull LinearLayout locationsListSelect,
      @NonNull TextView negativeTextview, @NonNull TextView positiveTextview,
      @NonNull TextView proportionTextview, @NonNull TextView textView2,
      @NonNull TextView textView5) {
    this.rootView = rootView;
    this.cardView = cardView;
    this.checkInButton = checkInButton;
    this.frameLayout2 = frameLayout2;
    this.locationNameTextView = locationNameTextView;
    this.locationNameTextview = locationNameTextview;
    this.locationsListSelect = locationsListSelect;
    this.negativeTextview = negativeTextview;
    this.positiveTextview = positiveTextview;
    this.proportionTextview = proportionTextview;
    this.textView2 = textView2;
    this.textView5 = textView5;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentViewLocationBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentViewLocationBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_view_location, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentViewLocationBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.cardView;
      CardView cardView = ViewBindings.findChildViewById(rootView, id);
      if (cardView == null) {
        break missingId;
      }

      id = R.id.check_in_button;
      Button checkInButton = ViewBindings.findChildViewById(rootView, id);
      if (checkInButton == null) {
        break missingId;
      }

      ConstraintLayout frameLayout2 = (ConstraintLayout) rootView;

      id = R.id.locationNameTextView;
      TextView locationNameTextView = ViewBindings.findChildViewById(rootView, id);
      if (locationNameTextView == null) {
        break missingId;
      }

      id = R.id.locationNameTextview;
      ConstraintLayout locationNameTextview = ViewBindings.findChildViewById(rootView, id);
      if (locationNameTextview == null) {
        break missingId;
      }

      id = R.id.locationsListSelect;
      LinearLayout locationsListSelect = ViewBindings.findChildViewById(rootView, id);
      if (locationsListSelect == null) {
        break missingId;
      }

      id = R.id.negative_textview;
      TextView negativeTextview = ViewBindings.findChildViewById(rootView, id);
      if (negativeTextview == null) {
        break missingId;
      }

      id = R.id.positive_textview;
      TextView positiveTextview = ViewBindings.findChildViewById(rootView, id);
      if (positiveTextview == null) {
        break missingId;
      }

      id = R.id.proportion_textview;
      TextView proportionTextview = ViewBindings.findChildViewById(rootView, id);
      if (proportionTextview == null) {
        break missingId;
      }

      id = R.id.textView2;
      TextView textView2 = ViewBindings.findChildViewById(rootView, id);
      if (textView2 == null) {
        break missingId;
      }

      id = R.id.textView5;
      TextView textView5 = ViewBindings.findChildViewById(rootView, id);
      if (textView5 == null) {
        break missingId;
      }

      return new FragmentViewLocationBinding((ConstraintLayout) rootView, cardView, checkInButton,
          frameLayout2, locationNameTextView, locationNameTextview, locationsListSelect,
          negativeTextview, positiveTextview, proportionTextview, textView2, textView5);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
