// Generated by view binder compiler. Do not edit!
package com.example.covidtrackertwo.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.covidtrackertwo.R;
import com.google.android.material.card.MaterialCardView;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class HistoryItemBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final TextView dateTextview;

  @NonNull
  public final MaterialCardView historyItemCardview;

  @NonNull
  public final TextView locationTextview;

  private HistoryItemBinding(@NonNull ConstraintLayout rootView, @NonNull TextView dateTextview,
      @NonNull MaterialCardView historyItemCardview, @NonNull TextView locationTextview) {
    this.rootView = rootView;
    this.dateTextview = dateTextview;
    this.historyItemCardview = historyItemCardview;
    this.locationTextview = locationTextview;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static HistoryItemBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static HistoryItemBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.history_item, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static HistoryItemBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.date_textview;
      TextView dateTextview = ViewBindings.findChildViewById(rootView, id);
      if (dateTextview == null) {
        break missingId;
      }

      id = R.id.history_item_cardview;
      MaterialCardView historyItemCardview = ViewBindings.findChildViewById(rootView, id);
      if (historyItemCardview == null) {
        break missingId;
      }

      id = R.id.location_textview;
      TextView locationTextview = ViewBindings.findChildViewById(rootView, id);
      if (locationTextview == null) {
        break missingId;
      }

      return new HistoryItemBinding((ConstraintLayout) rootView, dateTextview, historyItemCardview,
          locationTextview);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
