// Generated by view binder compiler. Do not edit!
package com.example.covidtrackertwo.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.covidtrackertwo.R;
import com.google.android.material.card.MaterialCardView;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class LocationItemBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final MaterialCardView locationItemCardview;

  @NonNull
  public final TextView locationNameTextview;

  private LocationItemBinding(@NonNull ConstraintLayout rootView,
      @NonNull MaterialCardView locationItemCardview, @NonNull TextView locationNameTextview) {
    this.rootView = rootView;
    this.locationItemCardview = locationItemCardview;
    this.locationNameTextview = locationNameTextview;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static LocationItemBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static LocationItemBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.location_item, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static LocationItemBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.location_item_cardview;
      MaterialCardView locationItemCardview = ViewBindings.findChildViewById(rootView, id);
      if (locationItemCardview == null) {
        break missingId;
      }

      id = R.id.location_name_textview;
      TextView locationNameTextview = ViewBindings.findChildViewById(rootView, id);
      if (locationNameTextview == null) {
        break missingId;
      }

      return new LocationItemBinding((ConstraintLayout) rootView, locationItemCardview,
          locationNameTextview);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
